version: "3"
services:
  app:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/Slim/.m2:/root/.m2"
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users-db